/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glb/art-gallery-mk1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Room.geometry} material={nodes.Room.material} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.door.geometry}
          material={nodes.door.material}
          position={[2.03, 16.03, 1.74]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.door_1.geometry}
          material={nodes.door_1.material}
          position={[2.03, 16.03, 1.74]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh geometry={nodes.Baseboard.geometry} material={nodes.Baseboard.material} />
        <mesh geometry={nodes.Floor.geometry} material={nodes.Floor.material} />
        <mesh
          geometry={nodes.Muro.geometry}
          material={nodes.Muro.material}
          position={[-0.08, 8.62, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[3.87, 1.71, 1.68]}
        />
        <mesh geometry={nodes.Ceiling.geometry} material={nodes.Ceiling.material} />
      </mesh>
      <mesh
        geometry={nodes.Mural.geometry}
        material={materials.mural}
        position={[301.79, 176.53, -276.15]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={212.28}
      />
      <mesh
        geometry={nodes.info.geometry}
        material={materials.info}
        position={[0.05, 208.41, -1473.02]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.C7.geometry}
        material={materials['7']}
        position={[41.25, 170.31, -862.25]}
        rotation={[0, 1.57, 0]}
        scale={208.14}
      />
      <mesh
        geometry={nodes.C6.geometry}
        material={materials['6']}
        position={[41.25, 170.31, -600]}
        rotation={[0, 1.57, 0]}
        scale={208.14}
      />
      <mesh
        geometry={nodes.C5.geometry}
        material={materials['5']}
        position={[594.02, 166.5, -542.77]}
        rotation={[0, -1.57, 0]}
        scale={212.28}
      />
      <mesh
        geometry={nodes.C4.geometry}
        material={materials['4']}
        position={[394.7, 170.31, -1400.29]}
        rotation={[0, -1.57, 0]}
        scale={186.16}
      />
      <mesh
        geometry={nodes.C3.geometry}
        material={materials['3']}
        position={[504.49, 170.31, -1194.1]}
        scale={208.14}
      />
      <mesh
        geometry={nodes.C2.geometry}
        material={materials['2']}
        position={[597.6, 174.69, -1063.05]}
        rotation={[0, -1.57, 0]}
        scale={128.91}
      />
      <mesh
        geometry={nodes.C1.geometry}
        material={materials['1']}
        position={[41.63, 162.08, -1140.85]}
        rotation={[0, 1.57, 0]}
        scale={200.9}
      />
    </group>
  )
}

useGLTF.preload('/glb/art-gallery-mk1.glb')
